FROM golang:1.15.2 AS builder

WORKDIR /go/src/github.com/Armatorix/BitLyke

COPY go.mod go.sum ./

RUN go mod download
COPY ./cmd ./cmd
COPY ./pkg ./pkg

RUN CGO_ENABLED=0 GOOS=linux go build -o main ./cmd/bitlyke

FROM scratch

WORKDIR /app
COPY --from=builder /go/src/github.com/Armatorix/BitLyke/main /app/

EXPOSE 8080

ENTRYPOINT [ "./main" ]