version: "3.3"

services:
  postgres:
    image: postgres:13.0
    ports:
      - "5432:5432"
    restart: always
    env_file: ../configs/env.local.pg
    volumes:
      - ../database/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build:
      dockerfile: docker/Dockerfile.api
      context: ../
    env_file: ../configs/env.local.api
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  swagger:
    image: swaggerapi/swagger-ui:v3.34.0
    environment:
      - SWAGGER_JSON=/api.yaml
    volumes:
      - ../api/openapi-spec/api.yaml:/api.yaml
    ports:
      - "80:8080"
