openapi: 3.0.3
# for online validation or view use https://editor.swagger.io/
servers:
  - url: "http://localhost:8081"

info:
  title: Bitlyke
  description: BITLY liKE API
  version: 0.1.0
paths:
  /short:
    get:
      description: Returns all shortened links
      responses:
        200:
          description: Proper list of shoretened links
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ShortenLinks"
        500:
          description: Internal server error
    post:
      description: Creates new link shortener
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ShortenLink"
      responses:
        201:
          description: Properly created link shortener
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ShortenLink"
        400:
          description: Provided bad request or missing data
        409:
          description: Url shortener already in use
        500:
          description: Internal server error
  /short/:lid:
    get:
      responses:
        301:
          description: Redirects to shortened link
        404:
          description: Not found record
    delete:
      responses:
        200:
          description: Properly deleted
        404:
          description: Not found
        500:
          description: Failed to delete

components:
  schemas:
    ShortenLinks:
      type: array
      items:
        $ref: "#/components/schemas/ShortenLink"
    ShortenLink:
      type: object
      properties:
        shorten_path:
          type: string
        real_url:
          type: string
