openapi: 3.0.3
# for online validation or view use https://editor.swagger.io/
servers:
  - url: "http://localhost:8080"

info:
  title: Bitlyke
  description: BITLY liKE API
  version: 0.1.0
paths:
  "/public/health-check":
    get:
      description: Verifies if service is healthy
      responses:
        200:
          description: healthy service
  "/api":
    get:
      description: Returns all short links
      responses:
        200:
          description: Proper list of short links
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ShortLinks"
        500:
          description: Internal server error
    post:
      description: Creates new short link
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ShortLink"
      responses:
        201:
          description: Properly created short link
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ShortLink"
        400:
          description: Provided bad request or missing data
        409:
          description: Short url already in use
        500:
          description: Internal server error
  "/api/{lid}":
    delete:
      description: Deletes the redirection pointed by lid
      parameters:
        - name: lid
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Properly deleted
        404:
          description: Not found
        500:
          description: Failed to delete
  "/{lid}":
    get:
      description: Redirects to the url pointed by lid
      parameters:
        - name: lid
          in: path
          required: true
          schema:
            type: string
      responses:
        307:
          description: Redirects to real link
        404:
          description: Not found record
        500:
          description: Unexpected error

components:
  schemas:
    ShortLinks:
      type: array
      items:
        $ref: "#/components/schemas/ShortLink"
    ShortLink:
      type: object
      properties:
        short_path:
          type: string
        real_url:
          type: string
