/*
 * WeightApp API
 *
 * Our dummy API for WeightAPP
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ShortenLink struct for ShortenLink
type ShortenLink struct {
	ShortenPath string `json:"shorten_path,omitempty"`
	RealUrl string `json:"real_url,omitempty"`
}
