/*
 * Bitlyke
 *
 * BITLY liKE API
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

// ShortLink struct for ShortLink
type ShortLink struct {
	ShortPath string `json:"short_path,omitempty"`
	RealUrl   string `json:"real_url,omitempty"`
}
